# apps

[cura]
src.github_tag = "Ultimaker/Cura"
src.include_regex = "5.\\d+\\.\\d+"
fetch.url = "https://github.com/Ultimaker/Cura/releases/download/$ver/Ultimaker-Cura-$ver-linux-X64.AppImage"

[discover-overlay]
src.github = "trigg/discover"
fetch.github = "trigg/discover"

[gpt4all]
src.git = "https://github.com/nomic-ai/gpt4all"
fetch.github = "nomic-ai/gpt4all"
git.fetchSubmodules = true

[uhk-agent]
src.github_tag = "UltimateHackingKeyboard/agent"
src.prefix = "v"
fetch.url = "https://github.com/UltimateHackingKeyboard/agent/releases/download/v$ver/UHK.Agent-$ver-linux-x86_64.AppImage"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true
cargo_locks = ["Cargo.lock"]

# fonts
[sf-compact]
src.manual = "unknown"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg"

[sf-mono]
src.manual = "unknown"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg"

[sf-pro]
src.manual = "unknown"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg"

[apple-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji.ttf"

[icat]
src.git = "https://github.com/nekowinston/icat"
fetch.github = "nekowinston/icat"
