name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "35 7 * * *"
jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - nekowinston
        cachixName:
          - nekowinston
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: "${{ matrix.nixPath }}"
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # TODO: build all packages in the repo with devour-flake, or similar
      - run: nix build -L .\#cura
      - run: nix build -L .\#discord-applemusic-rich-presence
        if: runner.os == 'macOS'
      - run: nix build -L .\#discover-overlay
      - run: nix build -L .\#helm-ls
      - run: nix build -L .\#jq-lsp
      - run: nix build -L .\#mopidy-podcast-itunes
      - run: nix build -L .\#org-stats
      - run: nix build -L .\#papirus-folders-catppuccin
      - run: nix build -L .\#picom-ft-labs
      - run: nix build -L .\#plymouth-theme-catppuccin
      - run: nix build -L .\#swww
      - run: nix build -L .\#vscode-extensions.ms-kubernetes-tools.vscode-kubernetes-tools
      - run: nix build -L .\#wezterm-nightly
      # TODO: enable if I ever add it to NUR
      # - name: Trigger NUR update
      #   # Don't replace <YOUR_REPO_NAME> here!
      #   if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      #   run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
