name: Build and populate cache

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "35 7 * * *"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        nurRepo: [nekowinston]
        cachixName: [nekowinston]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # TODO: build all packages in the repo with devour-flake, or similar
      - name: Build Linux packages
        run: |
          nix build -L --keep-going \
            .#apple-cursor \
            .#discover-overlay \
            .#mopidy-podcast-itunes \
            .#posy-improved-cursor \
            .#wezterm-nightly
        if: runner.os == 'Linux'

      - name: Build macOS packages
        run: |
          echo "currently no macOS packages to build"
        if: runner.os == 'macOS'

      - name: Build common packages
        run: |
          nix build -L --keep-going \
            .#gonvim-tools \
            .#helm-ls \
            .#icat \
            .#jq-lsp

      # TODO: enable if I ever add it to NUR
      # - name: Trigger NUR update
      #   # Don't replace <YOUR_REPO_NAME> here!
      #   if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      #   run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
