name: Build and populate cache

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "35 7 * * *"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        nurRepo: [nekowinston]
        cachixName: [nekowinston]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # TODO: build all packages in the repo with devour-flake, or similar
      - name: Build Linux packages
        run: |
          nix build -L .\#apple-cursor
          nix build -L .\#cura
          nix build -L .\#discover-overlay
          nix build -L .\#mopidy-podcast-itunes
          nix build -L .\#plymouth-theme-catppuccin
          nix build -L .\#posy-improved-cursor
        if: runner.os == 'Linux'

      - name: Build macOS packages
        run: |
          echo "currently no macOS packages to build"
        if: runner.os == 'macOS'

      - name: Build common packages
        run: |
          nix build -L .\#gonvim-tools
          nix build -L .\#helm-ls
          nix build -L .\#icat
          nix build -L .\#jq-lsp
          nix build -L .\#wezterm-nightly

      # TODO: enable if I ever add it to NUR
      # - name: Trigger NUR update
      #   # Don't replace <YOUR_REPO_NAME> here!
      #   if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      #   run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
