name: "Auto-update metadata"

on:
  schedule:
    - cron: "0 7 * * 1-6"
    - cron: "0 7 * * 0"
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update flake inputs
        run: "nix flake update"
        # Only do this once a week
        if: github.event.schedule == '0 7 * * 0'

      - name: Prefetch latest commits of packages
        run: "nix run github:berberman/nvfetcher"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metadata"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
